### ISSUE TITLE
Blockquotes look a bit intense

### ISSUE THREAD

**Issue by kholbekj** [mikemai2awesome/mcss#1]
Thanks a lot for the css, I find it very helpful!

Blockquotes are not suited to quote more than a couple of words, as they are very large. 

Is that by design?

**Comment by mikemai2awesome** [comment]
@kholbekj sorry for the late reply. I didn't know people are actually looking at this. So cool to find an issue here.

Yes, the blockquote is intended for pretty much a Pull Quote from the graphic design sense, since this framework is dedicated to a typographer and graphic design in general.

Obviously, if you use this, treat it like a reset. Since I wrote everything with `:where`, the specificity is low, you can easily write your own CSS to change any styles.
